### ISSUE TITLE
Proposal: Trailers

### ISSUE THREAD

**Issue by mariocosme** [markop159/KODI-Popcorn-Time#10]
First of all, tried this fork last night and it awesome: thank you for your work.

I would suggest that a button could be added to the media's information screen that could open the trailer. It would be nice to have all trailers, but I think movie's trailers are more important when compared to TV shows.

**Comment by markop159** [comment]
New version has working trailers for movies.

**Comment by mariocosme** [comment]
Works like a charm. Thank you!
