### ISSUE TITLE
Playback fails on Kodi 17.6/Libreelec

### ISSUE THREAD

**Issue by giaur500** [markop159/KODI-Popcorn-Time#100]
Kodi log:

10:42:55.385 T:3628069792 WARNING: CPythonInvoker(5, /storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py): the python script "/storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE
10:42:55.401 T:4096317536   ERROR: GetDirectory - Error getting plugin://plugin.video.kodipopcorntime/?action=last_added&categ=movies&endpoint=browse&mediaType=movies&order=-1
10:42:55.403 T:4096317536   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kodipopcorntime/?action=last_added&categ=movies&endpoint=browse&mediaType=movies&order=-1) failed
10:43:52.976 T:3556766624 WARNING: CPythonInvoker(6, /storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py): the python script "/storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE
10:44:02.885 T:3548378016  NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) error: [Errno 111] Connection refused
10:45:04.430 T:4096317536  NOTICE: Previous line repeats 41 times.
10:45:04.430 T:4096317536  NOTICE: VideoPlayer: Opening: http://127.0.0.1:5001/files/Suicide%20Squad%20%282016%29%20%5B1080p%5D%20%5BYTS.AG%5D/Suicide.Squad.2016.1080p.BluRay.x264-%5BYTS.AG%5D.mp4
10:45:04.431 T:4096317536 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
10:45:04.439 T:3548378016  NOTICE: Creating InputStream
10:45:04.467 T:3548378016   ERROR: Open - Unhandled exception
10:45:04.467 T:3548378016   ERROR: Open - Error opening http://127.0.0.1:5001/files/Suicide%20Squad%20%282016%29%20%5B1080p%5D%20%5BYTS.AG%5D/Suicide.Squad.2016.1080p.BluRay.x264-%5BYTS.AG%5D.mp4
10:45:04.467 T:3548378016   ERROR: CVideoPlayer::OpenInputStream - error opening [http://127.0.0.1:5001/files/Suicide%20Squad%20%282016%29%20%5B1080p%5D%20%5BYTS.AG%5D/Suicide.Squad.2016.1080p.BluRay.x264-%5BYTS.AG%5D.mp4]
10:45:04.468 T:3548378016  NOTICE: CVideoPlayer::OnExit()
10:45:04.483 T:4096317536  NOTICE: CVideoPlayer::CloseFile()
10:45:04.484 T:4096317536  NOTICE: VideoPlayer: waiting for threads to exit
10:45:04.484 T:4096317536  NOTICE: VideoPlayer: finished waiting
10:45:04.484 T:4096317536  NOTICE: CVideoPlayer::CloseFile()
10:45:04.484 T:4096317536  NOTICE: VideoPlayer: waiting for threads to exit
10:45:04.484 T:4096317536  NOTICE: VideoPlayer: finished waiting
10:45:14.581 T:3586278304 WARNING: [plugin.video.kodipopcorntime] (Torrent) Timeout occurred while shutting down torrent2http
10:45:14.581 T:3586278304 WARNING: [plugin.video.kodipopcorntime] (Torrent) Killing torrent2http
10:45:14.684 T:3586278304 WARNING: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py): the python script "/storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N14PythonBindings30XBMCAddon_xbmc_Player_DirectorE,N9XBMCAddon7xbmcgui14DialogProgressE,N9XBMCAddon7xbmcgui6WindowE,N9XBMCAddon7xbmcgui12ControlImageE,N9XBMCAddon7xbmcgui12ControlLabelE
10:45:14.761 T:3586278304  NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) error: [Errno 111] Connection refused
10:45:58.060 T:4096317536  NOTICE: Previous line repeats 32 times.
10:45:58.060 T:4096317536  NOTICE: VideoPlayer: Opening: http://127.0.0.1:44070/files/Suicide%20Squad%20%282016%29%20%5B1080p%5D%20%5BYTS.AG%5D/Suicide.Squad.2016.1080p.BluRay.x264-%5BYTS.AG%5D.mp4
10:45:58.060 T:4096317536 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
10:45:58.070 T:3586278304  NOTICE: Creating InputStream
10:45:58.114 T:3586278304   ERROR: Open - Unhandled exception
10:45:58.114 T:3586278304   ERROR: Open - Error opening http://127.0.0.1:44070/files/Suicide%20Squad%20%282016%29%20%5B1080p%5D%20%5BYTS.AG%5D/Suicide.Squad.2016.1080p.BluRay.x264-%5BYTS.AG%5D.mp4
10:45:58.116 T:3586278304   ERROR: CVideoPlayer::OpenInputStream - error opening [http://127.0.0.1:44070/files/Suicide%20Squad%20%282016%29%20%5B1080p%5D%20%5BYTS.AG%5D/Suicide.Squad.2016.1080p.BluRay.x264-%5BYTS.AG%5D.mp4]
10:45:58.116 T:3586278304  NOTICE: CVideoPlayer::OnExit()
10:45:58.138 T:4096317536  NOTICE: CVideoPlayer::CloseFile()
10:45:58.138 T:4096317536  NOTICE: VideoPlayer: waiting for threads to exit
10:45:58.138 T:4096317536  NOTICE: VideoPlayer: finished waiting
10:45:58.141 T:4096317536  NOTICE: CVideoPlayer::CloseFile()
10:45:58.141 T:4096317536  NOTICE: VideoPlayer: waiting for threads to exit
10:45:58.141 T:4096317536  NOTICE: VideoPlayer: finished waiting
10:46:03.490 T:3577889696 WARNING: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py): the python script "/storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui12ControlImageE,N9XBMCAddon7xbmcgui14DialogProgressE,N9XBMCAddon7xbmcgui6WindowE,N14PythonBindings30XBMCAddon_xbmc_Player_DirectorE,N9XBMCAddon7xbmcgui12ControlLabelE
10:46:03.976 T:3577889696  NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) error: [Errno 111] Connection refused
10:46:34.754 T:4096317536  NOTICE: Previous line repeats 37 times.
10:46:34.755 T:4096317536  NOTICE: VideoPlayer: Opening: http://127.0.0.1:56078/files/Logan%20%282017%29%20%5B1080p%5D%20%5BYTS.AG%5D/Logan.2017.1080p.BluRay.x264-%5BYTS.AG%5D.mp4
10:46:34.755 T:4096317536 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
10:46:34.761 T:3577889696  NOTICE: Creating InputStream
10:46:34.791 T:3577889696   ERROR: Open - Unhandled exception
10:46:34.791 T:3577889696   ERROR: Open - Error opening http://127.0.0.1:56078/files/Logan%20%282017%29%20%5B1080p%5D%20%5BYTS.AG%5D/Logan.2017.1080p.BluRay.x264-%5BYTS.AG%5D.mp4
10:46:34.791 T:3577889696   ERROR: CVideoPlayer::OpenInputStream - error opening [http://127.0.0.1:56078/files/Logan%20%282017%29%20%5B1080p%5D%20%5BYTS.AG%5D/Logan.2017.1080p.BluRay.x264-%5BYTS.AG%5D.mp4]
10:46:34.791 T:3577889696  NOTICE: CVideoPlayer::OnExit()
10:46:34.802 T:4096317536  NOTICE: CVideoPlayer::CloseFile()
10:46:34.803 T:4096317536  NOTICE: VideoPlayer: waiting for threads to exit
10:46:34.803 T:4096317536  NOTICE: VideoPlayer: finished waiting
10:46:34.803 T:4096317536  NOTICE: CVideoPlayer::CloseFile()
10:46:34.803 T:4096317536  NOTICE: VideoPlayer: waiting for threads to exit
10:46:34.803 T:4096317536  NOTICE: VideoPlayer: finished waiting
10:46:44.973 T:3548378016 WARNING: [plugin.video.kodipopcorntime] (Torrent) Timeout occurred while shutting down torrent2http
10:46:44.974 T:3548378016 WARNING: [plugin.video.kodipopcorntime] (Torrent) Killing torrent2http
10:46:45.077 T:3548378016 WARNING: CPythonInvoker(9, /storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py): the python script "/storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6WindowE,N9XBMCAddon7xbmcgui14DialogProgressE,N9XBMCAddon7xbmcgui12ControlLabelE,N14PythonBindings30XBMCAddon_xbmc_Player_DirectorE,N9XBMCAddon7xbmcgui12ControlImageE
11:01:47.794 T:3539989408  NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) error: [Errno 111] Connection refused
11:02:22.851 T:4096317536  NOTICE: Previous line repeats 43 times.
11:02:22.851 T:4096317536  NOTICE: VideoPlayer: Opening: http://127.0.0.1:5001/files/Inception%20%282010%29%20%5B1080p%5D/Inception.2010.1080p.BrRip.x264.YIFY.mp4
11:02:22.851 T:4096317536 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
11:02:22.867 T:3539989408  NOTICE: Creating InputStream
11:02:22.895 T:3539989408   ERROR: Open - Unhandled exception
11:02:22.895 T:3539989408   ERROR: Open - Error opening http://127.0.0.1:5001/files/Inception%20%282010%29%20%5B1080p%5D/Inception.2010.1080p.BrRip.x264.YIFY.mp4
11:02:22.896 T:3539989408   ERROR: CVideoPlayer::OpenInputStream - error opening [http://127.0.0.1:5001/files/Inception%20%282010%29%20%5B1080p%5D/Inception.2010.1080p.BrRip.x264.YIFY.mp4]
11:02:22.896 T:3539989408  NOTICE: CVideoPlayer::OnExit()
11:02:22.918 T:4096317536  NOTICE: CVideoPlayer::CloseFile()
11:02:22.918 T:4096317536  NOTICE: VideoPlayer: waiting for threads to exit
11:02:22.918 T:4096317536  NOTICE: VideoPlayer: finished waiting
11:02:22.918 T:4096317536  NOTICE: CVideoPlayer::CloseFile()
11:02:22.918 T:4096317536  NOTICE: VideoPlayer: waiting for threads to exit
11:02:22.918 T:4096317536  NOTICE: VideoPlayer: finished waiting
11:02:32.903 T:3586278304 WARNING: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py): the python script "/storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE,N14PythonBindings30XBMCAddon_xbmc_Player_DirectorE,N9XBMCAddon7xbmcgui6WindowE,N9XBMCAddon7xbmcgui12ControlImageE,N9XBMCAddon7xbmcgui12ControlLabelE
11:02:37.535 T:3577889696  NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) error: [Errno 111] Connection refused
11:03:22.801 T:4096317536  NOTICE: Previous line repeats 29 times.
11:03:26.774 T:4096317536  NOTICE: VideoPlayer: Opening: http://127.0.0.1:59778/files/Wonder%20Woman%20%282017%29%20%5B1080p%5D%20%5BYTS.AG%5D/Wonder.Woman.2017.1080p.BluRay.x264-%5BYTS.AG%5D.mp4
11:03:26.775 T:4096317536 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
11:03:26.781 T:3577889696  NOTICE: Creating InputStream
11:03:26.796 T:3577889696   ERROR: Open - Unhandled exception
11:03:26.796 T:3577889696   ERROR: Open - Error opening http://127.0.0.1:59778/files/Wonder%20Woman%20%282017%29%20%5B1080p%5D%20%5BYTS.AG%5D/Wonder.Woman.2017.1080p.BluRay.x264-%5BYTS.AG%5D.mp4
11:03:26.797 T:3577889696   ERROR: CVideoPlayer::OpenInputStream - error opening [http://127.0.0.1:59778/files/Wonder%20Woman%20%282017%29%20%5B1080p%5D%20%5BYTS.AG%5D/Wonder.Woman.2017.1080p.BluRay.x264-%5BYTS.AG%5D.mp4]
11:03:26.797 T:3577889696  NOTICE: CVideoPlayer::OnExit()
11:03:26.819 T:4096317536  NOTICE: CVideoPlayer::CloseFile()
11:03:26.819 T:4096317536  NOTICE: VideoPlayer: waiting for threads to exit
11:03:26.819 T:4096317536  NOTICE: VideoPlayer: finished waiting
11:03:26.819 T:4096317536  NOTICE: CVideoPlayer::CloseFile()
11:03:26.820 T:4096317536  NOTICE: VideoPlayer: waiting for threads to exit
11:03:26.820 T:4096317536  NOTICE: VideoPlayer: finished waiting
11:03:36.832 T:3586278304 WARNING: [plugin.video.kodipopcorntime] (Torrent) Timeout occurred while shutting down torrent2http
11:03:36.832 T:3586278304 WARNING: [plugin.video.kodipopcorntime] (Torrent) Killing torrent2http
11:03:36.944 T:3586278304 WARNING: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py): the python script "/storage/.kodi/addons/plugin.video.kodipopcorntime/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui14DialogProgressE,N9XBMCAddon7xbmcgui6WindowE,N14PythonBindings30XBMCAddon_xbmc_Player_DirectorE,N9XBMCAddon7xbmcgui12ControlLabelE,N9XBMCAddon7xbmcgui12ControlImageE
11:03:37.317 T:3586278304  NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) error: [Errno 111] Connection refused
11:04:07.712 T:4096317536  NOTICE: Previous line repeats 25 times.
11:04:07.712 T:4096317536  NOTICE: VideoPlayer: Opening: http://127.0.0.1:42262/files/Interstellar%20%282014%29%20%282014%29%20%5B1080p%5D/Interstellar.2014.2014.1080p.BluRay.x264.YIFY.mp4
11:04:07.712 T:4096317536 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
11:04:07.721 T:3586278304  NOTICE: Creating InputStream
11:04:07.741 T:3586278304   ERROR: Open - Unhandled exception
11:04:07.741 T:3586278304   ERROR: Open - Error opening http://127.0.0.1:42262/files/Interstellar%20%282014%29%20%282014%29%20%5B1080p%5D/Interstellar.2014.2014.1080p.BluRay.x264.YIFY.mp4
11:04:07.742 T:3586278304   ERROR: CVideoPlayer::OpenInputStream - error opening [http://127.0.0.1:42262/files/Interstellar%20%282014%29%20%282014%29%20%5B1080p%5D/Interstellar.2014.2014.1080p.BluRay.x264.YIFY.mp4]
11:04:07.742 T:3586278304  NOTICE: CVideoPlayer::OnExit()
11:04:07.758 T:4096317536  NOTICE: CVideoPlayer::CloseFile()
11:04:07.758 T:4096317536  NOTICE: VideoPlayer: waiting for threads to exit
11:04:07.759 T:4096317536  NOTICE: VideoPlayer: finished waiting
11:04:07.759 T:4096317536  NOTICE: CVideoPlayer::CloseFile()
11:04:07.759 T:4096317536  NOTICE: VideoPlayer: waiting for threads to exit
11:04:07.759 T:4096317536  NOTICE: VideoPlayer: finished waiting
11:04:48.220 T:3595563936 WARNING: [plugin.video.kodipopcorntime] (Torrent) Timeout occurred while shutting down torrent2http
11:04:48.220 T:3595563936 WARNING: [plugin.video.kodipopcorntime] (Torrent) Killing

Libreelec community build for Amlogic S905:

LibreELEC (wrxtasy-kszaq): 8.2.4.2-S905Test-1529136339, kernel: Linux ARM 64-bit version 3.14.29 aarch64

Any suggestions?

**Comment by markop159** [comment]
Hello!
This error:
`NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) error: [Errno 111] Connection refused`
usually occurs when you have firewall enabled on your system (I have seen this error on mac when it has fw enabled) and it is blocking torrent2http to connect.

I am not familiar with Amlogic devices, but I suppose that this LibreElec build is based on some linux distribution, can you check if you have enabled iptables firewall on this device and disable it or configure it to allow torrent2http to communicate with outside world.
