### ISSUE TITLE
could not receive media list as there is no domains that work

### ISSUE THREAD

**Issue by grfl** [markop159/KODI-Popcorn-Time#127]
Raspberry Pi 4 Libreelec Kodi

**Comment by Powershellder** [comment]
Sadly the devs keep screwing up/switching around APIs.
You could manually find the config file, but the comment from Daniel near the bottom simply has a link with an already set popcorn time location so its a matter of either using the install from zip option after downloading it or extracting it to the correct location yourself:

https://github.com/markop159/KODI-Popcorn-Time/issues/120

**Comment by sorin-pop** [comment]
I wonder when this will be properly released, updated (without me having to hack the code)? @markop159

**Comment by happydonut111** [comment]
Any word on this getting fixed?

**Comment by bcolombini** [comment]
@grfl @Powershellder @happydonut111 

I found solution on issue #120 follow link for the comment [https://github.com/markop159/KODI-Popcorn-Time/issues/120#issuecomment-614292593](https://github.com/markop159/KODI-Popcorn-Time/issues/120#issuecomment-614292593).

Or if you prefer can download on [ https://mega.nz/file/X9p1xaJS#wVhahPsH17HqUY1a0VvtwNLAlM8wKk-_1HTs4E_MqqA]( https://mega.nz/file/X9p1xaJS#wVhahPsH17HqUY1a0VvtwNLAlM8wKk-_1HTs4E_MqqA)

**Comment by tonibabura** [comment]
Since Yesterday I get same error : could not receive media list as there is no domains that work
Any news ?

**Comment by S0und** [comment]
@tonibabura install the updated plugin link the comment above yours. https://github.com/markop159/KODI-Popcorn-Time/issues/127#issuecomment-619318581

**Comment by happydonut111** [comment]
> @tonibabura install the updated plugin link the comment above yours. [#127 (comment)](https://github.com/markop159/KODI-Popcorn-Time/issues/127#issuecomment-619318581)

How would I do that on my television thats running Kodi? All I know how to do is download Kodi addons from repositories.

**Comment by S0und** [comment]
@happydonut111 

1. download the zip, and place it on your device, or on your network accessible by your device. 
2. uninstall your previous version of Kodi Popcorn Time
3. Settings -> Addons -> Install from zip file
4. find your previously downloaded zip file and install it.

**Comment by bcolombini** [comment]
@tonibabura follow the @S0und steps and you will have success.

**Comment by happydonut111** [comment]
> @happydonut111
> 
> 1. download the zip, and place it on your device, or on your network accessible by your device.

This is what I don’t understand. How would I place the zip “on my device”. It’s a television. Anyway, that’s for the help.

**Comment by bcolombini** [comment]
I never try on Smart Tv, i use raspbery 3. But i think, @happydonut111 , in your cause you should have a pendrive to transfer the zip file to your television, and follow the steps like @S0und told. 

good luck

**Comment by happydonut111** [comment]
Awesome man. Took your advice and it totally worked. Thanks for walking me through everything. Really appreciate the help!

**Comment by premudeshi** [comment]
I am getting the same issue, any help would be appreciated! I am on Raspberry Pi 3.

**Comment by bcolombini** [comment]
@premudeshi look here https://github.com/markop159/KODI-Popcorn-Time/issues/127#issuecomment-619318581

**Comment by premudeshi** [comment]
When I use the installer it fails to install. unknown error

**Comment by Tonio101** [comment]
@grfl Try the following:
SSH into your Kodi
vi /storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/favourites.py
change line 144
from: search = '%s/movie/%s' % ('https://tv-v2.api-fetch.website', fav['id'])
To: search = '%s/movie/%s' % ('https://tv-v2.api-fetch.sh', fav['id'])

Save the file

vi /storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/providers/api-fetch.py
Change Line 30
from: "https://tv-v2.api-fetch.website"
to: "https://tv-v2.api-fetch.sh"

Save the file

**Comment by daniel3xxx** [comment]
You guys can download 1.7.6 from here:
https://github.com/markop159/Markop159-repository/blob/3e11afd10a974d4038d94258ac9600859fd7c69b/Releases/plugin.video.kodipopcorntime/plugin.video.kodipopcorntime-1.7.6.zip
It was submited on 3rd of May but since then no answer from Markop159

**Comment by magic890** [comment]
@markop159 can we publish 1.7.6 in the repo and fix the issue without having to patch manually?
The latest available is 1.7.5 and still have this issue.

**Comment by MihaiChirculete** [comment]
> @grfl Try the following:
> SSH into your Kodi
> vi /storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/favourites.py
> change line 144
> from: search = '%s/movie/%s' % ('https://tv-v2.api-fetch.website', fav['id'])
> To: search = '%s/movie/%s' % ('https://tv-v2.api-fetch.sh', fav['id'])
> 
> Save the file
> 
> vi /storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/providers/api-fetch.py
> Change Line 30
> from: "https://tv-v2.api-fetch.website"
> to: "https://tv-v2.api-fetch.sh"
> 
> Save the file

This fix does not work for me, I am using kodi popcorntime 1.7.6 and added these fixes and it's still not able to load any content.
