### ISSUE TITLE
raspberry pi - tracker timeout

### ISSUE THREAD

**Issue by dnalexxio** [markop159/KODI-Popcorn-Time#16]
hi, i installed this plugins on many devices, without having problems. In my raspberry, with retropie and kodi installed, when i choose something to stream, the Fetching Information popup appers but it stucks there.
I only connected log in /dev/shm/runcommand.log

where i see that the torrent tracking information are searched, but then aborted like this:

sending announce (started)
torrent aborted "" (4)
Host not found (authoritative) "" (6)

This is not related to network problems because on the same network other devices work. Maybe this is not related to the plugins. Can you help me debug better?
thank you

**Comment by markop159** [comment]
@dnalexxio 
[Here](http://kodi.wiki/view/Log_file/Advanced) you have detailed documentation on how to enable debug logging in kodi and where is the log location. If you want to know what is happening whit my addon [enable debugging inside addon](https://github.com/markop159/KODI-Popcorn-Time/wiki/Discussions%2C-Proposals%2C-Issues-and-Bugs).

Additionally when you enable debug logging you will have the info in left upper corner with the log location.

**Comment by markop159** [comment]
Closed for now. Missing log.
