### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by Kidlike** [markop159/KODI-Popcorn-Time#17]
Opening ticket for adding stuff to favorites.

Maybe even one different favorite list per category (Movies / TV Shows / Anime)

**Comment by moebiuseye** [comment]
Hi! I can see that this feature is added, and I can add items to favorites using kodi version **16.1** 

However, I can't find how to get a list of the favorites. Was that implemented?

**Comment by markop159** [comment]
This is the Kodi's favourites. So you can find what you added to favourites in Kodi's favourites.

**Comment by moebiuseye** [comment]
Silly me. I didn't add your repo...

**Comment by markop159** [comment]
Next update will get favourites for TV shows and Anime. I Just need to test a little bit more...
