### ISSUE TITLE
Display movie rating

### ISSUE THREAD

**Issue by Kidlike** [markop159/KODI-Popcorn-Time#19]
Opening ticket for displaying movie rating.

**Comment by markop159** [comment]
can you please be more specific?

**Comment by Kidlike** [comment]
When you have a list of movies, to display ratings next to each (imdb or omdbapi).

**Comment by majki09** [comment]
I can see ratings in the wallpaper view. You can try it.

**Comment by markop159** [comment]
Rating is displayed on info page.
