### ISSUE TITLE
Finding subtitles in other languages than english

### ISSUE THREAD

**Issue by tobiasrj20** [markop159/KODI-Popcorn-Time#21]
Its not possible for me to find subtitles in Danish, even though I know they are on subscene?

**Comment by markop159** [comment]
@tobiasrj20 I will recommend you to use external plugin for subtitles (for example opensubtitles) and not the addon's feature of auto downloading (it is currently downloading from yifi subs and I think you cannot find all subtitles there). In the future when I find some free time I will try to change subtitle provider to opensubtitles.

**Comment by HeronSantosCom** [comment]
@tobiasrj20 I have had success with the plugin OpenSubtitle.org (Unofficial) 5.0.10 by amet,Mafarricos - SuperRepo.
