### ISSUE TITLE
V živo

### ISSUE THREAD

**Issue by jeancaffou** [markop159/KODI-Popcorn-Time#26]
Je možno dodati v plugin tudi možnost predvajanja v živo?

**Comment by markop159** [comment]
Kolikor jaz vem Popcorn Time nima ničesar kar bi se dalo predvajati v živo. Njihov API ima samo seznam filmov serij in animejev. Tako da prosim rezloži malo boljše kaj si imel v mislih.

**Comment by jeancaffou** [comment]
Se opravičujem, sem falil repozitorij. Feature request je bil mišljen za plugin rtvslo.

**Comment by markop159** [comment]
Bom odgovoril kar tukaj. Problem pri rtvslo live je ker za live streame uporabljajo octoshape ki pa v KODI-ju ni podprt... Če odpreš addon pod music addons pa imaš live radio. Če pa imaš kakšno idejo kako to implementirati sem odprt za predloge.

Tukaj bom ta issue zaprl, če pa imaš kakršen koli issue z rtvslo lahko komot napišeš nov issue pod rtvslo repositorijem.
