### ISSUE TITLE
File is not downloading in macOS and Krypton

### ISSUE THREAD

**Issue by HeronSantosCom** [markop159/KODI-Popcorn-Time#27]
Changing system, detected that the films/series are not downloading the plugin.

OS: **macOS Sierra (10.12.1)**
Kodi: **Kodi 17.0-BETA6 Git: 20161112-ae37dd6**
[popcorn.log.zip](https://github.com/markop159/KODI-Popcorn-Time/files/587727/popcorn.log.zip)

The log file is attached.

**Comment by markop159** [comment]
Answer in the issue #25
