### ISSUE TITLE
Fails on Fetching Content, movies only

### ISSUE THREAD

**Issue by Atheris84** [markop159/KODI-Popcorn-Time#28]
[openelec_log.txt](https://github.com/markop159/KODI-Popcorn-Time/files/601836/openelec_log.txt)

Fetching content fails trying to browse or search in movies, it seems to be a problem with trailers.

Commenting out "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/providers/api-fetch.py", line 143, seems to solve the problem

**Comment by markop159** [comment]
@Atheris84 first tnx for using my addon.
second tnx for pointing out the issue and attaching log, it looks like there were some changes in api (not all movies have trailers), so I fixed the code accordingly to api.

It should be fixed now just update to new version 1.6.1. Please close issue if it is fixed for you.
