### ISSUE TITLE
'action': "seeds"

### ISSUE THREAD

**Issue by freestylemaster** [markop159/KODI-Popcorn-Time#3]
Firstly, I appreciate the work. I just have some issue that I cannot fix myself;

'action': "seeds" seems to be having no effect on "Most Popular" section as it always lists "date_added". 
As far as I know this is also the default in api of yts.ag. "rating" seems to be working though.

Any idea how we can fix this?

**Comment by freestylemaster** [comment]
Update to myself:) 

I've did a manual request and it seems yts.ag does not list by seeds or peers. All I get is again date_added. So, I've contacted them to correct it if they would even care.

**Comment by markop159** [comment]
I really did not see this issue. Thanks for your comment and thanks for your efforts to contact yts team, let me know if they get back to you. :)

We can test with another providers. There are already 4 providers in code that I found on the internet, but I did not test them.

**Comment by freestylemaster** [comment]
Thanks. What are the providers I must have missed them. I will try if you could please list them

**Comment by markop159** [comment]
U can find them in [https://github.com/markop159/KODI-Popcorn-Time/blob/master/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/providers/movies_yify.py]

Here is the list of Movies providers in code:

domains = [
        "https://yts.ag",
        "https://yts.popcorntimece.ch",
        "https://movies.api-fetch.website",
        "http://eqwww.image.yt"
    ]

**Comment by freestylemaster** [comment]
Good news; https://movies.api-fetch.website seems to fetching by seeds fine.

**Comment by freestylemaster** [comment]
So, I no longer have issues. Thanks a lot for your work.

**Comment by markop159** [comment]
OK, ty for your time to test these providers.
I am glad you resolved your issue, will update this when I resolve my issues with tv show providers.
