### ISSUE TITLE
Suddenly not working anymore

### ISSUE THREAD

**Issue by jbakker81** [markop159/KODI-Popcorn-Time#32]
On multiple machines, running updated Arch x64. Also after deleting kodi user profile and installing again the same problem occurs: 

(terminal says this: 2016/12/15 11:21:51 Starting session... 2016/12/15 11:21:51 Address family not supported by protocol)

Log file: 

10:58:46 T:139914062591744   FATAL: [plugin.video.kodipopcorntime] Traceback (most recent call last):
                                              File "/home/htpc/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 37, in <module>
                                                getattr(gui, params.pop('endpoint', 'index'))(params.pop('mediaType', '')).show(**params)
                                              File "/home/htpc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/player.py", line 108, in show
                                                TorrentPlayer().playTorrentFile(self.mediaSettings, build_magnetFromMeta(params[quality], "quality %s" %quality), item, subtitle)
                                              File "/home/htpc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 432, in playTorrentFile
                                                raise Abort()
                                              File "/home/htpc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 42, in __exit__
                                                self.close()
                                              File "/home/htpc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 379, in close
                                                super(Loader, self).close()
                                              File "/home/htpc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 51, in close
                                                self.raiseAnyError()
                                              File "/home/htpc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 22, in ___run
                                                self._target()
                                              File "/home/htpc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 257, in _run
                                                if self._TEngine.start() and self._getPlayFile() and self._checkData() and self._preloading(self._item.get('stream_info', {}).get('video', {}).get('duration', 0)):
                                              File "/home/htpc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 122, in start
                                                raise TorrentError("Can't start torrent2http")
                                            TorrentError: Can't start torrent2http
10:58:46 T:139914062591744 WARNING: CPythonInvoker(4, /home/htpc/.kodi/addons/plugin.video.kodipopcorntime/addon.py): the python script "/home/htpc/.kodi/addons/plugin.video.kodipopcorntime/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N14PythonBindings30XBMCAddon_xbmc_Player_DirectorE,N9XBMCAddon7xbmcgui14DialogProgressE

**Comment by markop159** [comment]
can you provide full log with debugging enabled?

**Comment by jbakker81** [comment]
[kodi.log.txt](https://github.com/markop159/KODI-Popcorn-Time/files/691646/kodi.log.txt)

**Comment by markop159** [comment]
Please enable debug logging in kodi and debugging inside plugin ([how to](https://github.com/markop159/KODI-Popcorn-Time/wiki/Discussions%2C-Proposals%2C-Issues-and-Bugs)) and post newly created log here.

Make sure you have the latest version of plugin installed (currently 1.6.2)

**Comment by jbakker81** [comment]
[kodi.log.txt](https://github.com/markop159/KODI-Popcorn-Time/files/693315/kodi.log.txt)

**Comment by markop159** [comment]
Tnx for log, please download [this](https://github.com/markop159/KODI-Popcorn-Time/blob/master/test_builds/plugin.video.kodipopcorntime-1.6.3_test.zip) test build I hope i found the error, if it is not working I will try to install one VM with latest Arch X64 to test.

Please answer as soon as you can so I can update to new version. :)

**Comment by markop159** [comment]
Hi we are making progress, now I see that it gets the right binary path:
`13:49:20 T:140054384097024   DEBUG: [plugin.video.kodipopcorntime] (Thread-1) (Settings) movies.binary_path is '/home/htpc/.kodi/addons/plugin.video.kodipopcorntime/resources/bin/linux_x64/torrent2http'`

but I am surprised that it shows connection refused:
`13:49:20 T:140054384097024   DEBUG: [plugin.video.kodipopcorntime] (Thread-1) (URL) Trying to obtaining data from http://127.0.0.1:5001/status
13:49:20 T:140054384097024  NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) error: [Errno 111] Connection refused`

Did you try 2 times or just 1 time, because I think that the first time after update it does not work (for me first run gives an error but after this it works like it should.) but if you try again it should work.

**Comment by jbakker81** [comment]
I tried multiple times, also with the updated 1.6.4 version.

[kodi.log.txt](https://github.com/markop159/KODI-Popcorn-Time/files/697568/kodi.log.txt)

**Comment by markop159** [comment]
I guess there is something blocking torrent2http, so I will try to install Arch Linux on a VM and test it. I hope I find a working solution.

**Comment by markop159** [comment]
I managed to install the latest Arch Linux 64 bit on VM and installed Kodi plus my plugin. Tried to start a movie 1st time it crashed but then 2nd and 3rd time worked like a charm.

Do you use any software firewall on your system? Or maybe some other program that is already using 5001 port?

Can you try this 2 commands in terminal and give me the output:
`cd /home/htpc/.kodi/addons/plugin.video.kodipopcorntime/resources/bin/linux_x64/`

`./torrent2http -uri magnet:?xt=urn:btih:862f987d0395d31b0d9955a04d7700922523ce4e&dn=archlinux-2017.01.01-dual.iso&tr=udp://tracker.archlinux.org:6969&tr=http://tracker.archlinux.org:6969/announce`

This should run torrent2http with magnet link to Arch Linux download.

Then when this is running if you have gnome installed and some internet browser you can type into it:
`http://127.0.0.1:5001/status`

And it should give you some output about download.

**Comment by jbakker81** [comment]
Thanks for all your help. When doing this it outputs:

`./torrent2http --debug-alerts -uri magnet:?xt=urn:btih:862f987d0395d31b0d9955a04d7700922523ce4e&dn=archlinux-2017.01.01-dual.iso&tr=udp://tracker.archlinux.org:6969&tr=http://tracker.archlinux.org:6969/announce
[1] 24927
[2] 24928
[3] 24929
[2]-  Done                    dn=archlinux-2017.01.01-dual.iso
[3]+  Done                    tr=udp://tracker.archlinux.org:6969
htpc@i3 ~/.kodi/addons/plugin.video.kodipopcorntime/resources/bin/linux_x64 $ 2017/01/11 13:51:55 Starting session...
2017/01/11 13:51:55 Address family not supported by protocol
`
And then: This site can’t be reached 127.0.0.1 refused to connect.

Could it be the issue that i disabled ipv6 on my system?

**Comment by markop159** [comment]
Yes this is it, now that you mentioned it I tried to disable ipv6 with `ipv6.disable=1` kernel parameter and I get the same error `Address family not supported by protocol`.

But if you use `ipv6.disable_ipv6=1` kernel parameter will keep the IPv6 stack functional but will not assign IPv6 addresses to any of your network devices and the plugin works.

Please close the issue when the plugin starts working again.

**Comment by jbakker81** [comment]
Yeah enabling ipv6 makes it work again. There doesnt seem to be any option to pass to torrent2http to ignore ipv6. Maybe u had the binary compiled differently before. Case closed. Thanks for all your help!
