### ISSUE TITLE
Raspberry Pi Zero (armv6) - Stops at "Download starting" (Error 111: Connection refused)

### ISSUE THREAD

**Issue by Panoroma** [markop159/KODI-Popcorn-Time#33]
Hey there!

First off, thanks for continuing this project. You've done an excellent job, and I already have it working fine on my Raspberry Pi 2. However, my Pi Zero seems to be having problems.

I've tried installing and running KODI Popcorn Time 1.6.1 on my Pi Zero, and it manages to bring up the list of available films and everything, but when I try to watch any of them, all I get is a dialog box with "Download starting" for a few seconds. I've already read the logs and found out my Pi refuses to connect to the torrent trackers, which causes torrent2http to crash.

I've included the log file, and I hope you'll be able to shed some light on this issue.
OS: Raspbian Jessie. Kodi 16.1 Jarvis (not from the official repository, since that one's limited to 15.2).

Log file: http://pastebin.com/Q8448AUg

Edit: I meant "Starting", not "Download starting". My bad.

**Comment by markop159** [comment]
Hi you can try this version specifically designed for armv6:
https://github.com/markop159/KODI-Popcorn-Time/tree/master/test_builds

Download the second one, I think that Tv Shows are not working on this version but I can fix it if it will work.

**Comment by Panoroma** [comment]
Thank you so much for the response! Version 2 did the trick nicely, though 1080p movies cause caching issues and prevents continous playback. 720p seems to run wonderfully, though. And let's face it, for a 5 pound computer, the fact that it even runs Popcorn Time at 720p is quite an amazing feat.

Thanks again for the help!



On Sun, Dec 18, 2016 at 12:52 PM +0100, "Marko" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi you can try this version specifically designed for armv6:
https://github.com/markop159/KODI-Popcorn-Time/tree/master/test_builds

Download the second one, I think that Tv Shows are not working on this version but I can fix it if it will work.

**Comment by markop159** [comment]
Pi Zero is CPU vise on par with RPI 1 and 1080p is a bit too much for this CPU.

**Comment by Panoroma** [comment]
Yeah, that makes sense. I knew the Pi Zero had about the same specs, and I'm already amazed that it what it can do at such a price.
