### ISSUE TITLE
Cannot install from ZIP on Libreelec

### ISSUE THREAD

**Issue by Natrov** [markop159/KODI-Popcorn-Time#34]
15:46:50 178.970230 T:1963323392   ERROR: GetDirectory - Error getting zip://%2fvar%2fmedia%2fberryboot%2fplugin.video.kodipopcorntime.repository-1.1.0.zip/
15:52:50 539.278320 T:1963323392   ERROR: GetDirectory - Error getting zip://%2fvar%2fmedia%2fberryboot%2fplugin.video.kodipopcorntime-1.6.1.zip/

**Comment by markop159** [comment]
can you install any other plugins from zip?

If you cannot install other plugins from zip please open ticket on Libreelec.

**Comment by markop159** [comment]
not a plugin problem.
