### ISSUE TITLE
armv6 detection issue

### ISSUE THREAD

**Issue by juandocal** [markop159/KODI-Popcorn-Time#36]
## The environment
- Raspberry Pi Zero
- Openelec 15.x

## The problem
There are currently issues detecting armv6 architecture. If you see the arguments (`torrent_options`) being passed as part of:

`self._process = subprocess.Popen(torrent_options, stderr=self._logpipe, stdout=self._logpipe, startupinfo=startupinfo)`

You will then notice the version of torrent2http using is:

`/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/bin/linux_arm/torrent2http`

instead of:

`/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/bin/linux_armv6/torrent2http`

The result of trying to run the subprocess with these arguments is:

`runtime: this CPU has no VFPv3 floating point hardware, so it cannot run this GOARM=7 binary. Recompile using GOARM=5.`

Please note that I got this result by debugging it manually. In the normal logs this issue is represent by:

> NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) error: [Errno 111] Connection refused
> 
> File "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 122, in start
>     raise TorrentError("Can't start torrent2http")
> TorrentError: Can't start torrent2http

I haven't debug `platform.py` to see what do we get as part of `os.uname()`. I'll try to do it tomorrow.

## The _hacky_ solution
As part of making it work as soon as possible locally. I'm manually replacing the string in `torrent_options` to be:

`/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/bin/linux_armv6/torrent2http`

After doing it, the next error was `OSError: [Errno 13] Permission denied` So, after updating permissions within the armv6 directory I managed to make it work.

**Comment by markop159** [comment]
Hi you test build for ARMv6 here: [https://github.com/markop159/KODI-Popcorn-Time/tree/master/test_builds](https://github.com/markop159/KODI-Popcorn-Time/tree/master/test_builds)

2nd one is working.

I still did not had enough time to create a package that is working on all platforms.

**Comment by juandocal** [comment]
@markop159 I haven't tested it. What are the particular changes in that version? Apart from what I previously mentioned.

**Comment by markop159** [comment]
Timeout is a bit changed due to slow CPU on RPI 1. And it contains only ARMv6 binaries.

**Comment by markop159** [comment]
Hi new update v 1.6.2 have binnaries compiled for ARMv6 and it should work with RPI 1 and RPI Zero, please try and if it works close the issue.

**Comment by juandocal** [comment]
Sure. I'll give it later today.

**Comment by juandocal** [comment]
This issue has been resolved in v1.6.2 @markop159 I can see in the lists being fetched information about seeds and trailers. Is that somehow implemented and I'm missing the option enabling them? or is a work in progress?

**Comment by markop159** [comment]
Work in progress maybe sometime in the future.
