### ISSUE TITLE
Fetching content, nothing happens

### ISSUE THREAD

**Issue by mkacuba** [markop159/KODI-Popcorn-Time#37]
I had the same issue on OSMC and now on LibreElec. For 1 day movies worked, but I couldn't fetch the rest, like tv shows or anime. After clearing media information/media files in plugin settings I'm not able to fetch any list. "Fetching list" information appears and quickly disappears only when choosing options in movies category. In Tv shows/anime nothing appears. No reaction.
[kodi.zip](https://github.com/markop159/KODI-Popcorn-Time/files/685381/kodi.zip)

**Comment by markop159** [comment]
Hi I checked your log and I see errors like this:
`10:55:29 206.120865 T:1759941536   ERROR: [plugin.video.kodipopcorntime] (Thread-1) (URL) gaierror: [Errno -2] Name or service not known - https://api-fetch.website/tv/movies/1?genre=all&sort=trending&order=-1`

I guess that your DNS does not resolve the site correctly. You can try to change your DNS settings to google DNSs (8.8.8.8 and 8.8.4.4) I tried with my settings and with google DNSs and on my end it is working correctly (fetches movies, tv shows and anime)

You can try to open on your PC in web browser this: [https://api-fetch.website/tv/movies/1?genre=all&sort=trending&order=-1](https://api-fetch.website/tv/movies/1?genre=all&sort=trending&order=-1) and it should return some text like this (this is only a fraction of output):

`[{"_id":"tt2140479","imdb_id":"tt2140479","title":"The Accountant","year":"2016","synopsis":"As a math savant uncooks the books for a new client, the Treasury Department closes in on his activities and the body count starts to rise.","runtime":"128","released":1476403200,"certification":"R","torrents":{"en":{"1080p":{"url":"magnet:?xt=urn:btih:DEFA7D8218BAA4F3B0F54A7A7619911D83B11607&tr=udp://glotorrents.pw:6969/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://torrent.gresille.org:80/announce&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://p4p.arenabg.ch:1337&tr=udp://tracker.internetwarriors.net:1337","seed":7985,"peer":5746,"size":2093796557,"filesize":"1.95 GB","provider":"YTS"},"720p":{"url":"magnet:?xt=urn:btih:4E803A9D07492A5E8558D441B2A87B2B4ED67FDE&`

**Comment by LLeexx** [comment]
Same error here...
I check the logs and found this.

`10:13:16 T:140243793585920   FATAL: [plugin.video.kodipopcorntime] Traceback (most recent call last):
                                              File "<MyHOME>/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 37, in <module>
                                                getattr(gui, params.pop('endpoint', 'index'))(params.pop('mediaType', '')).show(**params)
                                              File "<MyHOME>/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/browse.py", line 45, in show
                                                pages = res['pages']
                                              File "/usr/lib/python2.7/contextlib.py", line 154, in __exit__
                                                self.thing.close()
                                              File "<MyHOME>/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/media.py", line 28, in close
                                                super(_Base, self).close()
                                              File "<MyHOME>/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 51, in close
                                                self.raiseAnyError()
                                              File "<MyHOME>/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 22, in ___run
                                                self._target()
                                              File "<MyHOME>/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/media.py", line 59, in _run
                                                self._data = self._provider_build_fn(_res, *self._args, **self._kwargs) # 1. Get request parameter. 2. Perform request. 3. Build item.
                                              File "<MyHOME>/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/providers/api-fetch.py", line 834, in browse_build
                                                item = _create_item(movie)
                                              File "<MyHOME>/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/providers/api-fetch.py", line 144, in _create_item
                                                "trailer": trailer
                                            UnboundLocalError: local variable 'trailer' referenced before assignment
`

Replace my home for \"\<MyHOME\>\"

**Comment by markop159** [comment]
I would need a bit more info:
OS, kodi version and plugin version.
And steps to recreate issue.

**Comment by LLeexx** [comment]
Sure @markop159 

Ubuntu 14.04 LTS updated
Kodi 16.1
Plugin 1.5.5.rc3

Steps. 

Start Kodi.
Select Videos.
Select Add-ons.
Select KODI Popcorn Time.
Select Movies.
Select "Most Popular" or any other option.

The fetching dialog appears for two seconds, and nothing... it stays on the same menu. 

The previous copy from the log file was doing that. 

The other options ( "Recently Added", etc.) with same result.

Thanks in advance...

**Comment by markop159** [comment]
Update ti plugin version 1.6.2

**Comment by LLeexx** [comment]
@markop159 Thanks.

It works!

Strange, previous repository never update the plugin. Well, thanks for this.

**Comment by markop159** [comment]
@mkacuba is your issue resolved? If it is can you close the issue or can you provide more info? OS, device, Kodi version and plugin version.

Additionally can you enable debug logging in Kodi and enable debugging in plugin and attach this logs.
[How to enable both is described in wiki.](https://github.com/markop159/KODI-Popcorn-Time/wiki/Discussions%2C-Proposals%2C-Issues-and-Bugs)
