### ISSUE TITLE
Play Kodi Popcorn Time from Super Favorites 

### ISSUE THREAD

**Issue by Zero0Q** [markop159/KODI-Popcorn-Time#4]
I'm trying to setup Kodi popcorn time to play movies from super favorites in iSearch but can't figure out this. Can anyone help with this?:
<favourite name="Kodi Popcorn Time" thumb="special://home/addons/plugin.video.kodipopcorntime/resources/icon.png">ActivateWindow(10025,&quot;plugin://plugin.video.kodipopcorntime/?endpoint=player&amp;mediaType=movies&amp;sf_options=fanart%3Dspecial%3A%2F%2Fhome%2Faddons%2Fplugin.video.kodipopcorntime%2Ffanart.jpg%26meta%3Dlabel%253DSearch%26_options_sf&quot;,return)</favourite>
Where do i put this [%SF%]
Thank you

**Comment by markop159** [comment]
Thanks for using KODI Popcorn Time plugin, but unfortunately I do not have experience with Super Favorites. Try asking for help developer of SF plugin.

**Comment by Zero0Q** [comment]
Thanks
