### ISSUE TITLE
Problem with opening

### ISSUE THREAD

**Issue by AyraBlack** [markop159/KODI-Popcorn-Time#43]
Hey!

After updated to 1.6.3 and 1.6.4, popcorn time does not start anymore. I just click it and that is all - nothing happens. With 1.6.2 everything was fine.
I am running kodi 16.1 on zidoo x9s. 

Can you help me figure it out? Thanks!

**Comment by markop159** [comment]
Can you please provide [logs](https://github.com/markop159/KODI-Popcorn-Time/wiki/Discussions%2C-Proposals%2C-Issues-and-Bugs)?

**Comment by AyraBlack** [comment]
Hey!

Finally think I managed - https://paste.ubuntu.com/23785717

Hope it helps and sorry!

**Comment by markop159** [comment]
@AyraBlack tnx for logs, try [this new test build](https://github.com/markop159/KODI-Popcorn-Time/blob/master/test_builds/plugin.video.kodipopcorntime-1.6.5-test.zip?raw=true).

If it works I will update repository with new version.

**Comment by AyraBlack** [comment]
​Thank you very much! Works like a charm! I have just one question: was it
because of my Android Box? I am running a Zidoo X9S..​

*Ana-Maria Udriste*
ana.m.udriste@gmail.com
anna.udriste@gmail.com  <anna.udriste@gmail.com>
*0726.245.291*

**Comment by markop159** [comment]
No it was because we changed some code and something went wrong for some people.

Will incorporate this fix in future updates.

**Comment by Linkzelda1509** [comment]
I had the same issue, it's works now with your test build!

**Comment by markop159** [comment]
I also updated in my repository to new working version.
