### ISSUE TITLE
Suggestion: Pulsar

### ISSUE THREAD

**Issue by kronflux** [markop159/KODI-Popcorn-Time#5]
Hey @markop159 , just wanted to thank you for your work so far, and also wanted to mention Pulsar might be worth looking into, it's a new and improved torrent streaming engine, which is far superior to xbmctorrent.

I had been considering rewriting it a while back similarly to how xbmctorrent was rewritten for this project, but I never got around to it due to life taking up most of my time these days.

A rewrite of Pulsar for Popcorntime might be a great way to refresh interest in this project, and possibly get some support from the Popcorntime community as well.

Just a thought! Keep up the great work :)

**Comment by markop159** [comment]
First thank you for your suggestion, I will look into it when I get more time.

I have been looking into adding TV shows section but it seems I just can not find enough time to implement this.

**Comment by kronflux** [comment]
life always takes priority, and it can get very busy lol.

Like I said, keep up the great work! I'll close this for now, thanks for responding :)
