### ISSUE TITLE
Migrate translations to Transifex

### ISSUE THREAD

**Issue by adamantike** [markop159/KODI-Popcorn-Time#56]
According to the [Language support](http://kodi.wiki/view/Language_support) wiki article, **xml** files have been deprecated, and the new standard are **po** files. By switching to _po_, we also can move the entire translation process to Transifex.

The steps to migrate to Transifex are detailed [here](http://forum.kodi.tv/showthread.php?tid=142736).

**Comment by markop159** [comment]
I agre about translations in po files.

About transifex I need to check it out.

**Comment by markop159** [comment]
@adamantike I created new branch for testing this po files.

I created [en_gb file](https://github.com/markop159/KODI-Popcorn-Time/tree/po_translations/plugin.video.kodipopcorntime/resources/language/resource.language.en_gb)

When I try this Language file and it does not work, I currently do not have time to debug this but you can check it out when you have time.

**Comment by markop159** [comment]
OK found the problem (typo) so I fixed en_GB file now it is working.

**Comment by markop159** [comment]
too old to be open.

**Comment by adamantike** [comment]
That doesn't mean the issue has magically disappeared.

**Comment by markop159** [comment]
No but I do not have time to do this. And this addon is not supported by Kodi team so it probably will never be transfered to Transifex.
