### ISSUE TITLE
Can't start torrent2http

### ISSUE THREAD

**Issue by Geremia** [markop159/KODI-Popcorn-Time#58]
The torrent2http in your release is is for hardware floating point ARM (ld-linux-armhf), but my Raspberry Pi installation is soft-floating point (ld-linux) installation. Is there a torrent2http binary that uses ld-linux and not ld-linux-armhf? thanks

**Comment by markop159** [comment]
Hi
I am not compiling torrent2http (I am using already compiled binaries) If you have the knowledge you can compile the binaries yourself (do not ask me how) or if you find already compiled binaries for your system you can just swap them in plugin's "bin" folder.

**Comment by Geremia** [comment]
> I am not compiling torrent2http (I am using already compiled binaries)
Where are you getting those?
Yes, perhaps I'll just compile it myself.

**Comment by markop159** [comment]
[here is the source](https://github.com/steeve/torrent2http)

**Comment by markop159** [comment]
Closed due to unsupported system.
