### ISSUE TITLE
CAPTCHA

### ISSUE THREAD

**Issue by gibbyJoe** [markop159/KODI-Popcorn-Time#6]
I was just wondering if there is any way to handle the CAPTCHA requests consequence of using a VPN. They prevent the update of the lists in KODI (Movie, Tv Shows, ...). Goes without saying, while using the plugin without VPN everything works just fine (hence, it is not a direct issue with the plugin but I was hoping to find a solution) :)

**Comment by markop159** [comment]
Hi I am afraid that I cannot help you in this situation. What about other addons that fetch data from internet, do they work via VPN?

**Comment by markop159** [comment]
I gues issue is not related to addon  so I will close it for now.
