### ISSUE TITLE
Browse for subtitle Kodi

### ISSUE THREAD

**Issue by tutelacooldouce** [markop159/KODI-Popcorn-Time#66]
Build :KODI 16.1 Git:327c53
OS: LibreELEC version: 7.0.3 (kernel 4.4.13)

Time to time, kodi do not permit me to choose a manually subtitle durring the movie show . 

How to reproduce : 
Pause the current movie playing and  go to "the menu movie" where we can control the movie play,stop, backward etc. etc..

-  choose > icon sounds (Audio and subtitle settings)

-   - and then > Browse for subtitle : 
At this point, Kodi should show me a File Manager where I can choose where my subtitle has been placed. 
Instead to have this choice . I got a root directory from nowhere not able to creat any directory.  and on the bottom of the screen we can see a local address with port. ie: http://127.0.0.1:43396

picture: [picture](http://imgur.com/a/Zeqj0)

May I ask you to fix it ? 

Thank you so much , 
tut.

**Comment by tutelacooldouce** [comment]
any update on it ? Are you able to reproduce the issue ? Do you recommend any specific action  ? 

Thanks,
tut.

**Comment by markop159** [comment]
I am using opensubtitles by opensubtitles.org addon to download subtitles if the popcorn time addon is not able to find subtitles automatically.

**Comment by tutelacooldouce** [comment]
me too , sometimes the specific subtitle do not exit on opensubtitles.org and other API service. 
That's why I would like to pick up manually.

**Comment by markop159** [comment]
OK I will try to look into this issue, but I cannot promise you anything because this is KODI functionality and I think it is not connected with my addon.

**Comment by tutelacooldouce** [comment]
sure. just let me know if it is your concerne otherise i will escalate to the kodi project.
please take in mind that is not happend everytime. but sporadicly
thanks

Le 17 févr. 2017 09:01, Marko <notifications@github.com> a écrit :

OK I will try to look into this issue, but I cannot promise you anything because this is KODI functionality and I think it is not connected with my addon.

**Comment by markop159** [comment]
I do not think they will do anything about this because this addon is not supported officially and never will be because it uses torrents for streaming videos.
