### ISSUE TITLE
Doesn't work on Kodi 18 - LibreELEC Testbuilds for RaspberryPi (Kodi 18.0)

### ISSUE THREAD

**Issue by ivangotoy** [markop159/KODI-Popcorn-Time#69]
Logs from kodi.log on raspberry pi 3.
http://pastebin.com/a0FMuMhu

**Comment by markop159** [comment]
Hi quick fix for you would be if you open this file on your RPI:
`/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/player.py`

And delete line 48:
`"duration": int(xbmc.getInfoLabel('ListItem.Duration') or 0),`

I will try to install Kodi 18 on one of my machines and properly fix this in next release.

Can you just post back if this fixes your issue.

**Comment by markop159** [comment]
you can try to change player.py file with [this one](https://github.com/markop159/KODI-Popcorn-Time/blob/master/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/player.py) and it should work.

**Comment by markop159** [comment]
No answer if this fixed the problem, closed for now.
