### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by Bekkenes** [markop159/KODI-Popcorn-Time#7]
Hello
Firstly, thanks for great work.
The program i get installed fine, i got latest version on my box.
I start program and go to movies, and i get up relevant information etc.
But when i try to launch a movie,tried about ten,  i get a progressbar  (i think) i think for about ten seconds.

Its an androidbox flashed with libelec and kodi running.

**Comment by markop159** [comment]
Thanks for testing
Can you please post logs, using [this guide](https://github.com/markop159/KODI-Popcorn-Time/wiki/Discussions%2C-Proposals%2C-Issues-and-Bugs), so I can take a look what went wrong.

**Comment by markop159** [comment]
Updated to Ver 1.5.1.b. Try to update and check if you still have this Issue.

**Comment by Bekkenes** [comment]
thanks, ill try later.

I been so busy i forgot to check with logging.

Thanks for the info :)


________________________________
Fra: Marko <notifications@github.com>
Sendt: 29. august 2016 13:29
Til: markop159/KODI-Popcorn-Time
Kopi: Bekkenes; Author
Emne: Re: [markop159/KODI-Popcorn-Time] not working for me (#7)


Updated to Ver 1.5.1.b. Try to update and check if you still have this Issue.

-

**Comment by markop159** [comment]
I will close this for now. If still not working open new Issue and attach log
