### ISSUE TITLE
How does host option work?

### ISSUE THREAD

**Issue by gacekssj4** [markop159/KODI-Popcorn-Time#72]
Not sure if its good place to ask for it. But documenation lacks explanation how does host option in advanced work?

Can I define my own source of torrents? For example, I would like only to see movies with polish dub or create such a source and use it.

**Comment by markop159** [comment]
host option is there just if the domain for api is down and api gets new domain, you can supply new domain name. It wont work with any api, it should be the same official popcorntime api and the same version.
