### ISSUE TITLE
Error on launch movie

### ISSUE THREAD

**Issue by joaosagrath** [markop159/KODI-Popcorn-Time#75]
Suddenly my movies or tv shows don´t launch... give a message: 
"An unknown error has ocurred"

Follow the log:

https://pastebin.com/8bk5NbKf

**Comment by markop159** [comment]
Hi I have not try to install KODI 18 leia already so I cannot test the fix right now. But as I can see from logs you can fix this by opening file on your system:
>  D:\Kodi\Agile\portable_data\addons\plugin.video.kodipopcorntime\resources\lib\kodipopcorntime\gui\player.py"

and delete line 48:
`"duration": int(xbmc.getInfoLabel('ListItem.Duration') or 0),`

save the file and it should work.

If this works please respond here so I can update the addon with this fix and upload.

**Comment by joaosagrath** [comment]
Deleted the line and give same message.

Here's the new log:

https://pastebin.com/wM0qJEhe

**Comment by markop159** [comment]
Hello I am sorry for late reply, I just installed Kodi 18 and tested to fix. Will upload new version in next few days, I just need to check if it is still working on Kodi 17...

For now to fix this issue you can just replace player.py file with this one and it should work:
[player.py](https://github.com/markop159/KODI-Popcorn-Time/blob/master/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/player.py)

**Comment by joaosagrath** [comment]
Hello!! thanks for the fix!!! now it's running! and very fast!

**Comment by markop159** [comment]
fixed
