### ISSUE TITLE
Subtitles not work

### ISSUE THREAD

**Issue by fernandogobah** [markop159/KODI-Popcorn-Time#78]
Subtitles do not appear. Apparently YTS no longer maintains the API

**Comment by markop159** [comment]
I am using opensubtitles plugin for kodi to download subtitles. yts api for subtitles never did work as it should.

**Comment by thiagosouza2000** [comment]
On my kodi, I can only choose YIFY Subtitles. How can I change it? Version 1.7.1 on an "android tv box"...

**Comment by markop159** [comment]
You can not change this inside addon, you need to install separately plugin for subtitles, I am using ["opensubtitles.org by opensubtitles"](https://www.tvaddons.ag/kodi-addons/show/service.subtitles.opensubtitles_by_opensubtitles/) and use it like you would use it for movies that are locally on your box.

I currently do not have time to remove this option from my addon or implement different provider for subtitles.

Hope it helps
