### ISSUE TITLE
TV Shows, Anime not working  

### ISSUE THREAD

**Issue by alahmass** [markop159/KODI-Popcorn-Time#8]
thanks a lot for the effort that has been done on this version, i was looking forward to have TV section to be added and you made it 💃 ,,, but unfortunately it's not working with me. once i click it, nothing happens. the movies section is working great as usual. i'm installing Kodi on Fire TV "4K version".

i have some wish list to have in the next release:
- Sort Movies by year.
- Sort Movies by rate G, PG, PG-13, R, NC-17, etc.
- New section for 4K movies :)
- Ability to browse torrent site such as RARBG and select any movie, because not all movies are shown in the current lists. or integrate torrent sites with your add on.

Thanks, and wish you all the best.

Sami

**Comment by markop159** [comment]
Hello, thanks for testing the addon. To resolve your issue please attach logs so I can see what is happening when you click on TV-Shows and Anime.

Currently I am using Popcorn-Time API so currently available sortings are described [here](https://popcorn-official.github.io/popcorn-api/manual/example.html#sorting). So for the next release I can only add Sort Movies by year.

**Comment by alahmass** [comment]
thanks a lot mark for your response, can you elaborate on how to save the logs via fire tv?

also, what about the remaining wish list, is there any plans for it in the future?

**Comment by alahmass** [comment]
by the way, i was mistaken, the TV shows working fine. the issue was on Movies when i select Movies by genre it sats " fetching content" then nothing happens.

**Comment by markop159** [comment]
I do not own a fire TV so I do not know where are the logs. You can try to find out how to get logs by reading [this](https://github.com/markop159/KODI-Popcorn-Time/wiki/Discussions%2C-Proposals%2C-Issues-and-Bugs). Otherwise I hope it will be fixed in next updates.

**Comment by markop159** [comment]
Fixed the issue and added sort by year for movies. Wait for next release.

**Comment by markop159** [comment]
Updated to Ver 1.5.1.b. Try to update and check if you still have this Issue.

**Comment by markop159** [comment]
I will close this for now.
