### ISSUE TITLE
A torrent error has occurred

### ISSUE THREAD

**Issue by paradoxgrowth** [markop159/KODI-Popcorn-Time#86]
Hi everyone,

Thanks so much for this amazing add in. I am running it in my Kodi version 16 within my qnap nas. I have installed it just down but it doesn't run anything. Every time I choose an episode, it just kicks up an error that says "a torrent error has occurred". I googled it and don't really see much for that error in relation to popcorn. Any ideas? Thanks so much for your help!

**Comment by albpara** [comment]
+1

Same error on LibreElec on Raspberry Pi, sometines it just stays on "Fetching information"

**Comment by paradoxgrowth** [comment]
I notice that the problem could be that it is NOT finding seeds. How can we fix this?

**Comment by albpara** [comment]
Ingot this error even whem triyng to watch a popular movie. But the error is not aleats the same gor me... the first time I try to watch a movie after rebooting the raspberry, I got someething like “Unknown torren error”

**Comment by paradoxgrowth** [comment]
To be clear I have the same “Unknown torrent error” message. I just noticed that there are no seeds found. This could be linked to the problem.


I was wondering where to find the logs myself. If someone knows please let me know. Thanks

**Comment by albpara** [comment]
But I got that error on most popular torrents... those play just fine on my computer

How did you know that the problem behind was that? Is possible to gat any debug information?

**Comment by paradoxgrowth** [comment]
I second that, could someone tell us where to find log files so we could pinpoint the problem? thanks!

**Comment by gitfamhub** [comment]
Got the same error, here's my logs:
https://pastebin.com/raw/ZwBVjjAt

**Comment by gitfamhub** [comment]
For the record, I'm on an ODROID-C2.

**Comment by kryss05** [comment]
i confirm, i have same error in OSX hight sierra clean install.. in windows running perfectly. Please someone post a solve solution. Plss plss plss.

**Comment by markop159** [comment]
@paradoxgrowth qnap is not supported, there are no binnaries of torrent2http for qnap.

@kryss05 On macOS, firewall is blocking torrent2http data transfer.

@gitfamhub from the log i suspect that something is blocking torrent2http from executing on your linux device. Can you login to your device via ssh and go to the folder "/storage/.kodi/addons/plugin.video.kodipopcorntime/resources/bin/linux_x64" and execute "sudo chmod +x torrent2http"

**Comment by mgmaqueda** [comment]
Hi,
I got the same error running the popcorn time add-on on Kodi. I tried the solution given to @gitfamhub but didn't work. Any ideas!
Thank you!!

**Comment by markop159** [comment]
@mgmaqueda 
I will need some more info:
Kodi version, OS, addon version, device this is running on, logs...

**Comment by smoonlee** [comment]
@markop159 i've got the same problem running Kodi 17.4 on Volumio2. This is all running on a Raspberry Pi 3B+

**Comment by smoonlee** [comment]
Stupid question, where can I pull the logs from?

**Comment by markop159** [comment]
https://github.com/markop159/KODI-Popcorn-Time/wiki/Discussions%2C-Proposals%2C-Issues-and-Bugs

**Comment by smoonlee** [comment]
Cheers, - Sods Law you posted that and it started working! 

can close the topic

**Comment by markop159** [comment]
resolved itself
