### ISSUE TITLE
Fetches info then nothing, FATAL

### ISSUE THREAD

**Issue by kronflux** [markop159/KODI-Popcorn-Time#9]
EDIT: to fix formatting and make it easier to read, uploaded to GIST

https://gist.githubusercontent.com/kronflux/23465444a674a83fc315b7da5d50a299/raw/83ba8745dd6c92f7452b9c4314aa4bc34162e0f3/kodi.log

**Comment by markop159** [comment]
I know about this FATAL errors about metadata, but the addon should work anyway.

Can you please enable debug logging and internal addon logging using [this](https://github.com/markop159/KODI-Popcorn-Time/wiki/Discussions%2C-Proposals%2C-Issues-and-Bugs) and please describe steps what you are doing.

**Comment by kronflux** [comment]
That was with plugin's debug on, but here's one with Kodi's on as well.
It had a lot of repeated messages(by a lot, I mean hundreds of thousands of lines) so I tried to clean it up a bit without losing any critical information.
https://gist.githubusercontent.com/kronflux/d99e98adf5a2ae26f647776337c73357/raw/03765d650170a04e09e49768cc658cbc6581b52f/gistfile1.txt

Movies DO work, I confirmed that just now, I think last time was just coincidence that it didn't work, because it's working pretty reliably now.
This is from the Anime section.

**Comment by markop159** [comment]
Thanks for this log. This is the issue with the mime type for ".mkv" files. Some versions of operating systems do not see mkv files as video files. I already found this issue on Android device and it is already fixed. Wait for another release or replace torrent.py file in addon with [this new one](https://github.com/markop159/KODI-Popcorn-Time/blob/master/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py).

**Comment by markop159** [comment]
Updated to Ver 1.5.1.b. Try to update and check if you still have this Issue.

**Comment by kronflux** [comment]
Yep! all is working now, although I will mention it didn't show up in the repo as an update, had to manually download.

**Comment by markop159** [comment]
I am glad it is working for you now.

Sometimes in kodi you need to manualy "check for update" under "System -> Add-ons" to see new update.
