### ISSUE TITLE
[Request] Add to Official Kodi Repository

### ISSUE THREAD

**Issue by zero77** [markop159/KODI-Popcorn-Time#96]
Can you please add the KODI-Popcorn-Time addon to the official Kodi repository so, it can be installed and updated from within Kodi without having to add any other repositories to Kodi.
Thanks

**Comment by alvarogalia** [comment]
I think it isn't possible due to legal reasons.
Basically, if kodi promote popcorn time they are promoting piracy

**Comment by markop159** [comment]
wont happen, kodi comunity would never allow this to be in official repo.
